### ISSUE TITLE
socket to connect

### ISSUE THREAD

**Issue by moosavimaleki** [zyberspace/php-telegram-cli-client#11]
hi

i don't understand!!

i want send massage to telegram.

``` php
$telegram = new \Zyberspace\Telegram\Cli\Client('unix:///tmp/tg.sck');
```

what is 'unix:///tmp/tg.sck' ?

how active it in windows(local host) or linux server?

how active my phone number on this telegram client?!

**Comment by gojigeje** [comment]
hi
`unix:///tmp/tg.sck` is socket file created by _telegram-cli_ (https://github.com/vysheng/tg/), please read the project readme first coz it's already mentioned there: https://github.com/zyberspace/php-telegram-cli-client#setup-telegram-cli.

Basically you need to setup/activate your telegram number on _telegram-cli_ first, then run _telegram-cli_ on that particular unix-socket file, then this _telegram-cli-client_ can connect to it.

**Comment by zyberspace** [comment]
thx @gojigeje for the correct answer. Will close this now :)

**Comment by moosavimaleki** [comment]
@zyberspace  and @gojigeje  Thanks

sorry
i have a question
i want use it in windows !!
what i do ?!

thanks
