### ISSUE TITLE
change_user_group: can't find the user telegramd to switch to bind: Address already in use

### ISSUE THREAD

**Issue by Raakh** [zyberspace/php-telegram-cli-client#12]
Hello,

I just seen your API today and tried to install it. I placed your files on dedicated server and used this command:
 tg/bin/telegram-cli --json -dWS /tmp/tg.sck &
[1] 13619
[root@serverName httpdocs]# change_user_group: can't find the user telegramd to switch to
bind: Address already in use

Why its displaying message "bind: Address already in use"

Best regards

**Comment by Raakh** [comment]
Hello,

Still waiting for your kind reply

Best regards

**Comment by ztl8702** [comment]
This page may be helpful: https://github.com/vysheng/tg/issues/349

**Comment by zyberspace** [comment]
Hi, sry for the late answer but the problem is probably that there is already a socket named `tg.sck` in `/tmp/`. Just try to delete it and you should be fine (`rm -f /tmp/tg.sck`) or use a different name for the socket.
