### ISSUE TITLE
telegram-cli crash when received invalid command

### ISSUE THREAD

**Issue by dausruddin** [zyberspace/php-telegram-cli-client#15]
I tried to send this

`$telegram->exec('msg "user#id81958936" "hei"');`

user id shouldnt be put into quote, so telegram-cli dies. Is it normal? 
This mean that telegram will crash if received invalid command right?

**Comment by zyberspace** [comment]
Yeah this is a problem with the telegram-cli, that's why we have the command-wrappers in the `Client`-class which tests the parameters before sending it to the cli.

Gonna close this issue now as there is not much we can do about it from the php-perspective.
