### ISSUE TITLE
Listen to incoming message

### ISSUE THREAD

**Issue by natsu90** [zyberspace/php-telegram-cli-client#17]
How do I listen to incoming message?

**Comment by mfuentesg** [comment]
I would use other language to hear the incoming messages like ruby or python.

`while (true) ....`

**Comment by moosavimaleki** [comment]
while(true) ?!

i want function that return new messages
for example:

$msgs=pollNewMessage();
foreach($msgs as $msg){
 save in DB
}

**Comment by zyberspace** [comment]
Hi, you can use [`getHistory()`](https://phpdoc.zyberware.org/zyberspace/telegram-cli-client/classes/Zyberspace.Telegram.Cli.Client.html#method_getHistory) to get the latest messages from a specific peer.

There is no method to get all new messages from every peer so you will need to check for changes in [`getDialogList()`](https://phpdoc.zyberware.org/zyberspace/telegram-cli-client/classes/Zyberspace.Telegram.Cli.Client.html#method_getDialogList). Just compare the response twith the last one.

**Comment by halanegonzaga** [comment]
I try use:
`$telegram->exec('main_session');` this return objects with info about: updates, new messages, online/offline

You can be add a function then return json from call `$this->exec('main_session')` in lib/Zyberspace/Telegram/Cli/Client.php

^-^
