### ISSUE TITLE
Setting api_id and api_ahsh manually

### ISSUE THREAD

**Issue by ariel12345** [zyberspace/php-telegram-cli-client#18]
How can I login to api set manually , perhaps someone will send sample code for sending a simple text message including a connection to the api , please help me

**Comment by zyberspace** [comment]
Hi this is not possible with the telegram-cli (which suites this library as backend). You maybe want to take a look in the [unoffical telegram-bot-sdk for php](https://github.com/irazasyed/telegram-bot-sdk).
