### ISSUE TITLE
It dosen't work ..

### ISSUE THREAD

**Issue by ghost** [zyberspace/php-telegram-cli-client#2]
Hi ,

Thank you for amazing classes to use tg with PHP

I am using it but dosn't work, I use (Ubuntu ) , also I use Telegram-cli and it is works fine.

I opened the terminal and print: ./bin/telegram-cli -dWS /tmp/tg.sck & ( reurned this: [3] 10809 ).

then I installed (php-telegram-cli-client) by composer , create a new index.php file and use same example code.

but when I try to run file , dosn't happen , no return data.

**Comment by jonnywilliamson** [comment]
Well I'm currently using it daily at the moment without issues so it's hard to know what exactly is the problem, perhaps you should provide more info like your code in index.php etc.

I'm still waiting for a PR to be merged so we can add more features... (hint hint!)

**Comment by zyberspace** [comment]
Hi, pls try `./bin/telegram-cli -vWS /tmp/tg.sck`.
The`-v` increases the verbosity and shows you when someone connects over the socket.
Should look kinda like this if you then run your php-script:

```
 *** Accepting incoming connection
 *** Read from incoming connection
 *** Read from incoming connection
 [16:24]  random_user <<< hey :D
 *** Closing incoming connection
```

**Comment by DennyDai** [comment]
when I try to run file , dosn't happen , no return data too. 
and run ./bin/telegram-cli -vWS /tmp/tg.sck. bash can run. but php not.

**Comment by DennyDai** [comment]
i have solved this problem. change permission of tg.sck to 0777

**Comment by zyberspace** [comment]
> change permission of tg.sck to 0777

From the [man-page](http://manpages.ubuntu.com/manpages/vivid/en/man7/unix.7.html#contenttoc5):

> Connecting to the socket object requires read/write permission. This behavior differs from many BSD-derived systems which ignore permissions for UNIX domain sockets.  Portable programs should not rely on this feature for security.

My default-rights for sockets are 0775, so only user and group can access it.
I will insert a note into the README to ensure it is readable if created by another user / group, thx :)

**Comment by zyberspace** [comment]
Hi @dennydai, i finally added the information to the README and gave you some credit. Thx for it :wink:

**Comment by DennyDai** [comment]
you're welcome:wink:
