### ISSUE TITLE
Channels

### ISSUE THREAD

**Issue by MohamadSH** [zyberspace/php-telegram-cli-client#20]
Hi,
First of all I have to thank you for this developing such great PHP package. I have a question:
Is there any functions in order to work with channels? For example getting the list of your channels or posting on them or most importantly accessing your channel's member list?
Thank you very much.

**Comment by zyberspace** [comment]
Hi, there are no methods to work with channels in this project as they were released after i had no time to work on this project anymore and there will be no new features added in the future.

Sadly even the [unoffical telegram-bot-sdk for php](https://github.com/irazasyed/telegram-bot-sdk/) has no way to interact with channels.  
Maybe you can create a new issue over there and ask for channel-support. :)
