### ISSUE TITLE
Unicode Characters

### ISSUE THREAD

**Issue by Exlord** [zyberspace/php-telegram-cli-client#22]
HI,
Unicode character are being send as ???? .
Can u fix this?

**Comment by Exlord** [comment]
sorry my bad, my file had the wrong encoding :D
Can't seems to be able to delete the issue

**Comment by nesttle** [comment]
Same here, how did you solved this? @Exlord

Thanks!

**Comment by Exlord** [comment]
@nesttle  as I said in my case my file was saved with different encoding, it should have benn unicode or utf8

But if your problem is with the database you should use utf8mb4 for the collation and encoding in the DB
