### ISSUE TITLE
Channels support

### ISSUE THREAD

**Issue by ingria** [zyberspace/php-telegram-cli-client#26]
There are a lot of features in Telegram CLI, which are not supported in Telegram Bot API (and not sure if ever will). One of them is channels support. So this project is still highly useful for developers :wink: 

I am successfully using your lib for interacting with channels. Should i PR?

**Comment by zyberspace** [comment]
Hi, PRs are always welcome so feel free to open one!
But i have a codacy bot running on this project so beware that he will probably comment some things.

However, if it's only about the coding style, i have no problem with fixing the (coding style) problems myself after merging it so just ignore him if he complains about some spaces. :)
