### ISSUE TITLE
addContact() failed on 32bit version of php --> 32bit's INT value limit.

### ISSUE THREAD

**Issue by gojigeje** [zyberspace/php-telegram-cli-client#3]
The `addContact()` method parses `$phoneNumber` to integer.
On 32bit version of php, problem will occur when receiving 11 or 12 character of number (e.g. 6212345678901, typical phone number nowadays usually consists up  to  11 or 12 character).

I know this is not a big problem and can just be resolved by using 64bit version of php, but if there's a workaround to 32bit php it would be super awesome :+1: .

**Comment by zyberspace** [comment]
Thx for the info, did not thought about this. Fixed it now.
