### ISSUE TITLE
Ability to send Links / Pictures

### ISSUE THREAD

**Issue by uppaljs** [zyberspace/php-telegram-cli-client#5]
Hi,

Is there a plan to implement ability to send pictures ?

Thanks,

**Comment by zyberspace** [comment]
Yeah, i already added the helper method for it.
But group chat comes first. ;D

What do you mean exactly with links? Shouldn't you be able to just paste them as normal text?

**Comment by juanbits** [comment]
Hi @zyberspace i have some solution, but i cant write a push .. 

i get an error 403.. how can i add this changes?

**Comment by zyberspace** [comment]
Closed as i have no time to work on this project anymore and there won't be any new features.
